# Generated by Django 4.2.7 on 2025-08-04 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0004_alter_cliente_es_distribuidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Distribuidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('BASICO', 'Básico'), ('PREMIUM', 'Premium')], default='BASICO', max_length=10)),
                ('cantidad_dominios', models.PositiveIntegerField(default=0)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_distribuidor', to='Clientes.cliente')),
            ],
        ),
    ]
