# Generated by Django 4.2.7 on 2025-08-07 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Distribuidor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribuidor',
            name='paginas_vendidas',
            field=models.PositiveIntegerField(default=0, help_text='Cantidad de páginas ya vendidas'),
        ),
        migrations.AlterField(
            model_name='distribuidor',
            name='cantidad_dominios',
            field=models.PositiveIntegerField(default=0, help_text='Total de páginas compradas'),
        ),
    ]
