# Generated by Django 5.2.4 on 2025-07-25 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('nombre_titular', models.CharField(max_length=50)),
                ('fecha_expiracion', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=4)),
            ],
        ),
    ]
