# Generated by Django 5.2.4 on 2025-07-28 06:32

import Pagos.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TarjetaCredito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16, validators=[Pagos.validators.validar_tarjeta])),
                ('nombre_titular', models.CharField(max_length=50)),
                ('fecha_expiracion', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=4)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='Clientes.cliente')),
            ],
        ),
    ]
