# Generated by Django 5.2.4 on 2025-07-26 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_remove_cliente_direccionid_remove_cliente_tarjetaid_and_more'),
        ('Pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarjetacredito',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='Clientes.cliente'),
            preserve_default=False,
        ),
    ]
