# Generated by Django 5.2.4 on 2025-08-05 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoDistribuidor',
            fields=[
                ('pago_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Pagos.pago')),
                ('cantidad_paginas', models.PositiveIntegerField()),
                ('descripcion', models.CharField(blank=True, help_text="Detalle opcional de la compra (ej: 'paquete de 100 páginas')", max_length=255)),
            ],
            bases=('Pagos.pago',),
        ),
    ]
