# Generated by Django 5.2.4 on 2025-07-27 20:45

import Pagos.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0002_tarjetacredito_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarjetacredito',
            name='numero',
            field=models.CharField(max_length=16, validators=[Pagos.validators.validar_tarjeta]),
        ),
    ]
