# Generated by Django 5.2.4 on 2025-07-28 06:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('paisId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Pais',
                'verbose_name_plural': 'Paises',
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccionId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ubicacion', models.CharField(max_length=50)),
                ('codigoPostal', models.CharField(max_length=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones', to='Clientes.cliente')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Direcciones.pais')),
            ],
        ),
    ]
