# Generated by Django 5.2.4 on 2025-07-25 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('paisId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('direccionId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('ubicacion', models.CharField(max_length=50)),
                ('codigoPostal', models.CharField(max_length=10)),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Direcciones.pais')),
            ],
        ),
    ]
