# Generated by Django 4.2.7 on 2025-08-06 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0005_alter_cliente_es_distribuidor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dominios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreDominio', models.CharField(max_length=255, unique=True)),
                ('clienteId', models.ForeignKey(db_column='clienteId', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
            ],
            options={
                'db_table': 'Dominios',
            },
        ),
    ]
