# Generated by Django 4.2.7 on 2025-08-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dominios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dominios',
            name='compraDistribuidor',
            field=models.BooleanField(default=False, help_text='Indica si el dominio fue comprado por un distribuidor'),
        ),
    ]
