# Generated by Django 4.2.7 on 2025-08-03 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='nivel',
            field=models.IntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3')], default=1, verbose_name='nivel de acceso'),
        ),
    ]
