# Generated by Django 5.2.4 on 2025-07-25 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Direcciones', '0001_initial'),
        ('Pagos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('clienteId', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nickname', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=20)),
                ('contrasena', models.CharField(max_length=15, verbose_name='contraseña')),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('metodoPago', models.BooleanField(default=False, verbose_name='método de pago')),
                ('direccionID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Direcciones.direccion')),
                ('tarjetaID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagos.tarjetacredito')),
            ],
        ),
    ]
