# Generated by Django 5.2.4 on 2025-08-02 07:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono', models.IntegerField(blank=True)),
                ('tiene_suscripcion', models.BooleanField(default=False)),
                ('plan', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inicio_suscripcion', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin_suscripcion', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
