# Generated by Django 4.2.7 on 2025-08-03 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
    ]
