# Generated by Django 5.2.4 on 2025-07-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='direccionID',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='tarjetaID',
        ),
        migrations.AddField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(default='Sin Nombre', max_length=15, verbose_name='nombre'),
        ),
    ]
