# Generated by Django 5.2.4 on 2025-08-04 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0002_auto_20250803_0912'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='es_distribuidor',
            field=models.BooleanField(default=False),
        ),
    ]
