# Generated by Django 4.2.7 on 2025-08-04 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0003_cliente_es_distribuidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='es_distribuidor',
            field=models.BooleanField(default=True),
        ),
    ]
