# Generated by Django 5.2.4 on 2025-08-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clientes', '0004_alter_cliente_es_distribuidor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='es_distribuidor',
            field=models.BooleanField(default=False),
        ),
    ]
