# Generated by Django 5.2.4 on 2025-08-04 01:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Clientes', '0002_auto_20250803_0912'),
        ('Empleados', '0002_empleado_nivel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('idEstado', models.IntegerField(primary_key=True, serialize=False)),
                ('nombreEstado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Estado',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('idTicket', models.AutoField(primary_key=True, serialize=False)),
                ('nombreTicket', models.CharField(max_length=50)),
                ('descripcionTicket', models.CharField(max_length=250)),
                ('fechar_creacion', models.DateField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(db_column='clienteId', on_delete=django.db.models.deletion.CASCADE, to='Clientes.cliente')),
            ],
            options={
                'db_table': 'Ticket',
            },
        ),
        migrations.CreateModel(
            name='HistoriaTicket',
            fields=[
                ('idCambioTicket', models.AutoField(primary_key=True, serialize=False)),
                ('modDescripcion', models.CharField(max_length=250)),
                ('fecha_modificacion', models.DateField(default=django.utils.timezone.now)),
                ('empleado', models.ForeignKey(blank=True, db_column='idEmpleado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Empleados.empleado')),
                ('estado', models.ForeignKey(db_column='idEstado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='Tickets.estado')),
                ('ticket', models.ForeignKey(db_column='idTicket', on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='Tickets.ticket')),
            ],
            options={
                'db_table': 'HistoriaTicket',
            },
        ),
    ]
