PLANES_DISPONIBLES = {
    'Plata': {
        'precio_mensual': 5,
        'precio_semestral': 25,
        'precio_anual': 45,
        'webs': 2,
        'bases_datos': 20,
        'almacenamiento': '20 GB NVMe SSD',
        'correos': 20,
        'ssl': 2,
        'https': True,
        'creador_sitios': True,
        'email_marketing': True,
    },
    'Platino': {
        'precio_mensual': 8,
        'precio_semestral': 40,
        'precio_anual': 72,
        'webs': 3,
        'bases_datos': 40,
        'almacenamiento': '40 GB NVMe SSD',
        'correos': 40,
        'ssl': 3,
        'https': True,
        'creador_sitios': True,
        'email_marketing': True,
    },
    'Oro': {
        'precio_mensual': 11,
        'precio_semestral': 55,
        'precio_anual': 99,
        'webs': 5,
        'bases_datos': 'ilimitadas',
        'almacenamiento': '60 GB NVMe SSD',
        'correos': 60,
        'ssl': 5,
        'https': True,
        'creador_sitios': True,
        'email_marketing': True,
    },
}